name: Publish to NPM
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.1
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Use Node.js
      uses: actions/setup-node@v4.0.4
      with:
        node-version-vile: .nvmrc
        registry-url: 'https://registry.npmjs.org'
        scope: "@clxrity"
        cache: 'pnpm'
  
    - run: pnpm run ci
    - run: npm publish --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}